In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [3]:
from scipy import linalg, sparse

In [56]:
def form_laplacian(n):
    A_0_sparse = sparse.diags(diagonals=[-1.0, 2.0, -1.0], offsets = [-1, 0, 1], shape=(n, n))
    return A_0_sparse.tocsc()

In [120]:
b = 2
num_blocks = 7
n = (b-1)*num_blocks + b-1

In [121]:
transformation_mat = sparse.lil_matrix((n, n))
curr_idx = 0

for i in range(n):
    if (i+1) % b == 0:
        continue
    transformation_mat[i, curr_idx] = 1
    curr_idx += 1
    
for i in range(1,num_blocks-1):
    transformation_mat[i*b-1, curr_idx] = 1
    curr_idx += 1

IndexError: row index (9) out of bounds

In [122]:
transformation_mat.todense()

matrix([[1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1.]])

In [88]:
(transformation_mat @ form_laplacian(n) @ transformation_mat.T).todense()

matrix([[ 2.,  0., -1.,  0.],
        [ 0.,  2., -1., -1.],
        [-1., -1.,  2.,  0.],
        [ 0., -1.,  0.,  2.]])

In [87]:
form_laplacian(n).todense()

matrix([[ 2., -1.,  0.,  0.],
        [-1.,  2., -1.,  0.],
        [ 0., -1.,  2., -1.],
        [ 0.,  0., -1.,  2.]])