In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [3]:
from scipy import linalg, sparse

In [56]:
def form_laplacian(n):
    A_0_sparse = sparse.diags(diagonals=[-1.0, 2.0, -1.0], offsets = [-1, 0, 1], shape=(n, n))
    return A_0_sparse.tocsc()

In [89]:
b = 2
num_blocks = 6
n = (b-1)*num_blocks + b-1

In [98]:
transformation_mat = sparse.csc_matrix((n, n))
curr_idx = 0

for i in range(n):
    if (i+1) % b == 0:
        continue
    transformation_mat[i, curr_idx] = 1
    curr_idx += 1
    
for i in range(0,num_blocks-2):
    transformation_mat[i*(b-1)+b-1, curr_idx] = 1
    curr_idx += 1

/anaconda3/lib/python3.6/site-packages/scipy/sparse/compressed.py:746: SparseEfficiencyWarning: Changing the sparsity structure of a csc_matrix is expensive. lil_matrix is more efficient.
  SparseEfficiencyWarning)


IndexError: index (7) out of range (>= 7)

In [91]:
transformation_mat.todense()

matrix([[1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0.]])

In [88]:
(transformation_mat @ form_laplacian(n) @ transformation_mat.T).todense()

matrix([[ 2.,  0., -1.,  0.],
        [ 0.,  2., -1., -1.],
        [-1., -1.,  2.,  0.],
        [ 0., -1.,  0.,  2.]])

In [87]:
form_laplacian(n).todense()

matrix([[ 2., -1.,  0.,  0.],
        [-1.,  2., -1.,  0.],
        [ 0., -1.,  2., -1.],
        [ 0.,  0., -1.,  2.]])